# Site settings
baseurl = "https://celinelenoble.com/"
languageCode = "en-us"
title = "Celine Lenoble Portfolio"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-83885416-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "celinelenobledotcom"

SectionPagesMenu = "main"

[params]
	name = "Celine Lenoble"
	description = "Celine Lenoble Portfolio"
	bio = "User Research - Experience Design"
	# Enter optionally your twitter account
	twitter = "@CelineLenoble"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = ["css/custom.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""

	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = "404 - Page not found"
	subtitle404 = "This content doesn't seem to exist. Please check the URL or browse the posts below."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

	sectionMenus = ["portfolio", "blog"]

	[params.portfolio]
		readMore = "Other projects"

	[params.blog]
		readMore = "Latest posts"

# Add additional social link entries underneath
[social]
    github = "https://github.com/clenoble"
	twitter  = "https://www.twitter.com/CelineLenoble"
    linkedin = "https://www.linkedin.com/in/celinelenoble"
	stack-exchange = "https://ux.stackexchange.com/users/105777/celine"
	



